/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Activities
         * @description CONTRACTS §4 documents `city_id`, `category`, `cost_max`. `q`/`limit`/
         *     `offset` are additive conveniences for the Activity Search screen.
         *
         *     `category` is typed as the enum, so an unknown value is a clean 422
         *     rather than a silent empty result set.
         */
        get: operations["search_activities_activities_get"];
        put?: never;
        /** Create Activity */
        post: operations["create_activity_activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Activity */
        get: operations["read_activity_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Activity */
        patch: operations["update_activity_activities__activity_id__patch"];
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description OAuth2 password flow. The spec fixes the form field name as `username`;
         *     GlobeTrotter carries the user's EMAIL in it (see the CONTRACTS §3 note).
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create a user with a bcrypt-hashed password and return an access token.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Cities
         * @description Query params are exactly those documented in CONTRACTS §4 — `q`,
         *     `country`, `cost_max`, `sort`. `limit`/`offset` are added for paging;
         *     they are additive and change no documented behaviour.
         */
        get: operations["search_cities_cities_get"];
        put?: never;
        /**
         * Create City
         * @description Catalog write — gated to catalog_manager/admin (CONTRACTS §5).
         */
        post: operations["create_city_cities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities/{city_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read City */
        get: operations["read_city_cities__city_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update City */
        patch: operations["update_city_cities__city_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itinerary-activities/{itinerary_activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Itinerary Activity */
        delete: operations["delete_itinerary_activity_itinerary_activities__itinerary_activity_id__delete"];
        options?: never;
        head?: never;
        /** Update Itinerary Activity */
        patch: operations["update_itinerary_activity_itinerary_activities__itinerary_activity_id__patch"];
        trace?: never;
    };
    "/public/trips/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Public Trip
         * @description Read-only itinerary for anyone holding the link. No write actions exposed.
         */
        get: operations["read_public_trip_public_trips__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/trips/{token}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy Public Trip
         * @description Duplicate a shared trip under the current user (CONTRACTS §6).
         *
         *     Requires auth — the frontend sends unauthenticated visitors to
         *     `/login?redirect=...` first. The copy is a private, independent trip:
         *     sharing state is deliberately NOT carried over, so copying someone's
         *     public itinerary never republishes it under a new owner.
         */
        post: operations["copy_public_trip_public_trips__token__copy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder Stops
         * @description Apply a whole new ordering in ONE request (CONTRACTS §4: batched, never
         *     one call per row) — a drag-reorder in the builder is a single write.
         *
         *     Every stop must belong to the same trip, and that trip must be one the
         *     caller may touch. Both are checked before anything is mutated, so a
         *     partially-authorized batch changes nothing at all.
         */
        patch: operations["reorder_stops_stops_reorder_patch"];
        trace?: never;
    };
    "/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Stop */
        delete: operations["delete_stop_stops__stop_id__delete"];
        options?: never;
        head?: never;
        /** Update Stop */
        patch: operations["update_stop_stops__stop_id__patch"];
        trace?: never;
    };
    "/stops/{stop_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stop Activities */
        get: operations["list_stop_activities_stops__stop_id__activities_get"];
        put?: never;
        /**
         * Add Stop Activity
         * @description Schedule a catalog activity on this stop.
         *
         *     `cost` defaults from `Activity.cost` at insert time and is independent
         *     from then on (CONTRACTS §2), so re-pricing the catalog later never
         *     rewrites a planned trip's numbers.
         */
        post: operations["add_stop_activity_stops__stop_id__activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trips
         * @description Trips owned by the current user, soonest departure first.
         */
        get: operations["list_trips_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Trip
         * @description A trip plus its ordered stops, with the §7.2 computed fields.
         */
        get: operations["read_trip_trips__trip_id__get"];
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Trip
         * @description Update a trip.
         *
         *     Toggling `is_public` is owner-only (CONTRACTS §5) and mints the share
         *     token on first publish. The token is never regenerated on later
         *     publishes (CONTRACTS §2), so a link already shared with someone keeps
         *     working after a private/public round trip.
         */
        patch: operations["update_trip_trips__trip_id__patch"];
        trace?: never;
    };
    "/trips/{trip_id}/auto-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto Plan
         * @description Fill the trip with a real, editable draft itinerary.
         *
         *     Always returns a usable plan: if Groq is unreachable or its output fails
         *     DB validation, the deterministic scorer covers the gap (CONTRACTS §7.1).
         *     The response echoes the full stop list so the frontend can drop the user
         *     straight into the Itinerary Builder without a second round trip.
         */
        post: operations["auto_plan_trips__trip_id__auto_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Budget
         * @description Live aggregation — never a stored or cached total (ARCHITECTURE §5).
         */
        get: operations["read_budget_trips__trip_id__budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stops */
        get: operations["list_stops_trips__trip_id__stops_get"];
        put?: never;
        /**
         * Create Stop
         * @description Add a city leg. Both cross-row date rules run before the insert
         *     (services/stops.py) rather than being re-derived here.
         */
        post: operations["create_stop_trips__trip_id__stops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Update name, language, and/or the saved-destinations list.
         */
        patch: operations["update_me_users_me_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityCategory
         * @description The ONLY valid category values anywhere in the system (CONTRACTS.md
         *     §2, §8) — budget-breakdown grouping, seed data, and frontend filters
         *     all depend on this exact set. Add a value here first if it's ever
         *     needed, never ad hoc in one layer.
         * @enum {string}
         */
        ActivityCategory: "sightseeing" | "food" | "adventure" | "transport" | "stay" | "other";
        /**
         * ActivityCreate
         * @description POST /activities — catalog_manager only (CONTRACTS §4/§5).
         */
        ActivityCreate: {
            category: components["schemas"]["ActivityCategory"];
            /**
             * City Id
             * Format: uuid
             */
            city_id: string;
            /** Cost */
            cost?: number | string | null;
            /** Description */
            description?: string | null;
            /** Duration Hours */
            duration_hours?: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Name */
            name: string;
        };
        /** ActivityRead */
        ActivityRead: {
            category: components["schemas"]["ActivityCategory"];
            /**
             * City Id
             * Format: uuid
             */
            city_id: string;
            /** Cost */
            cost?: string | null;
            /** Description */
            description?: string | null;
            /** Duration Hours */
            duration_hours?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /** Name */
            name: string;
        };
        /** ActivityUpdate */
        ActivityUpdate: {
            category?: components["schemas"]["ActivityCategory"] | null;
            /** City Id */
            city_id?: string | null;
            /** Cost */
            cost?: number | string | null;
            /** Description */
            description?: string | null;
            /** Duration Hours */
            duration_hours?: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * AutoPlanRequest
         * @description POST /trips/{id}/auto-plan body.
         */
        AutoPlanRequest: {
            /** Budget Target */
            budget_target?: number | string | null;
            /** Interest Categories */
            interest_categories?: components["schemas"]["ActivityCategory"][];
            /**
             * Pace
             * @default balanced
             * @enum {string}
             */
            pace: "relaxed" | "balanced" | "packed";
            /** Preferences */
            preferences?: string | null;
        };
        /**
         * AutoPlanResponse
         * @description What the assistant actually wrote.
         *
         *     `source` records which path produced the plan (CONTRACTS §7.1 asks for
         *     this to be logged for the demo narrative) — it is diagnostic, not
         *     user-facing copy.
         */
        AutoPlanResponse: {
            /** Activities Created */
            activities_created: number;
            /** Estimated Total */
            estimated_total: string;
            /**
             * Source
             * @enum {string}
             */
            source: "llm" | "fallback" | "llm+fallback";
            /**
             * Stops
             * @default []
             */
            stops: components["schemas"]["StopRead"][];
            /** Stops Created */
            stops_created: number;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /**
         * BudgetRead
         * @description GET /trips/{id}/budget.
         *
         *     Every figure here is computed at request time from a GROUP BY over
         *     ItineraryActivity.cost — none of it is a stored column (ARCHITECTURE §5).
         */
        BudgetRead: {
            /** Amount By Category */
            amount_by_category: {
                [key: string]: string;
            };
            /** Amount Per Day */
            amount_per_day: string;
            /** Amount Total */
            amount_total: string;
            /** Budget Target */
            budget_target?: string | null;
            /** Duration Days */
            duration_days: number;
            /** Is Over Budget */
            is_over_budget?: boolean | null;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
        };
        /**
         * CityBrief
         * @description Enough of a City to render a saved-destination chip on the profile.
         */
        CityBrief: {
            /** Country */
            country: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * CityCreate
         * @description POST /cities — catalog_manager only (CONTRACTS §4/§5).
         *
         *     latitude/longitude are required, not optional: CONTRACTS §2 makes them
         *     non-negotiable because the route map and the distance calc are silently
         *     useless without them.
         */
        CityCreate: {
            /** Cost Index */
            cost_index?: number | null;
            /** Country */
            country: string;
            /** Google Place Id */
            google_place_id?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Popularity */
            popularity?: number | null;
        };
        /** CityRead */
        CityRead: {
            /** Cost Index */
            cost_index?: number | null;
            /** Country */
            country: string;
            /** Google Place Id */
            google_place_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Popularity */
            popularity?: number | null;
        };
        /**
         * CityUpdate
         * @description PATCH /cities/{id} — every field optional, but lat/lng may never be nulled.
         */
        CityUpdate: {
            /** Cost Index */
            cost_index?: number | null;
            /** Country */
            country?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Name */
            name?: string | null;
            /** Popularity */
            popularity?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItineraryActivityCreate
         * @description POST /stops/{id}/activities (CONTRACTS §4).
         *
         *     `cost` is optional on the way in: when omitted the route copies
         *     `Activity.cost` at insert time (CONTRACTS §2). Passing it explicitly
         *     lets a user record what they actually expect to pay for this trip.
         */
        ItineraryActivityCreate: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Cost */
            cost?: number | string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Scheduled Time */
            scheduled_time?: number | null;
        };
        /** ItineraryActivityRead */
        ItineraryActivityRead: {
            activity?: components["schemas"]["ActivityRead"] | null;
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Cost */
            cost?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes?: string | null;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Scheduled Time */
            scheduled_time?: number | null;
            /**
             * Stop Id
             * Format: uuid
             */
            stop_id: string;
        };
        /** ItineraryActivityUpdate */
        ItineraryActivityUpdate: {
            /** Cost */
            cost?: number | string | null;
            /** Notes */
            notes?: string | null;
            /** Scheduled Date */
            scheduled_date?: string | null;
            /** Scheduled Time */
            scheduled_time?: number | null;
        };
        /**
         * PublicTripRead
         * @description Read-only trip served by GET /public/trips/{token}.
         *
         *     Deliberately NOT TripRead: this response carries no `id`, no `user_id`,
         *     and no `share_token`. A public viewer gets the itinerary, never the
         *     internal ids that would let them probe authenticated routes, and never
         *     a token they could reshare beyond the one they already hold.
         */
        PublicTripRead: {
            /** Amount Total */
            amount_total: string;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /**
             * Date End
             * Format: date
             */
            date_end: string;
            /**
             * Date Start
             * Format: date
             */
            date_start: string;
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Owner Name */
            owner_name: string;
            /**
             * Stops
             * @default []
             */
            stops: components["schemas"]["StopRead"][];
        };
        /**
         * StopCreate
         * @description POST /trips/{id}/stops.
         *
         *     `sequence` is optional: omit it and the route appends the stop to the
         *     end of the trip, which is what the Itinerary Builder does for every
         *     "add city" click. The cross-row date rules (CONTRACTS §2) are checked
         *     in services/stops.py at write time, not here.
         */
        StopCreate: {
            /**
             * City Id
             * Format: uuid
             */
            city_id: string;
            /**
             * Date End
             * Format: date
             */
            date_end: string;
            /**
             * Date Start
             * Format: date
             */
            date_start: string;
            /** Sequence */
            sequence?: number | null;
        };
        /**
         * StopRead
         * @description Stop as returned by the API.
         *
         *     The last five fields are computed per request by services/feasibility.py
         *     (CONTRACTS §7.2) — they are NOT columns. The frontend displays them and
         *     never recomputes any of them itself (CONTRACTS §8).
         */
        StopRead: {
            city?: components["schemas"]["CityRead"] | null;
            /**
             * City Id
             * Format: uuid
             */
            city_id: string;
            /**
             * Date End
             * Format: date
             */
            date_end: string;
            /**
             * Date Start
             * Format: date
             */
            date_start: string;
            /** Distance From Previous Km */
            distance_from_previous_km?: number | null;
            /** Distance Source */
            distance_source?: ("directions" | "haversine") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Feasible
             * @default true
             */
            is_feasible: boolean;
            /**
             * Itinerary Activities
             * @default []
             */
            itinerary_activities: components["schemas"]["ItineraryActivityRead"][];
            /** Sequence */
            sequence: number;
            /** Travel Duration Hours */
            travel_duration_hours?: number | null;
            /** Travel Gap Days */
            travel_gap_days?: number | null;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
        };
        /** StopReorderItem */
        StopReorderItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sequence */
            sequence: number;
        };
        /** StopUpdate */
        StopUpdate: {
            /** City Id */
            city_id?: string | null;
            /** Date End */
            date_end?: string | null;
            /** Date Start */
            date_start?: string | null;
            /** Sequence */
            sequence?: number | null;
        };
        /**
         * Token
         * @description CONTRACTS §3 response shape: {access_token, token_type: "bearer"}.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TripCreate */
        TripCreate: {
            /** Budget Target */
            budget_target?: number | string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /**
             * Date End
             * Format: date
             */
            date_end: string;
            /**
             * Date Start
             * Format: date
             */
            date_start: string;
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /**
         * TripDetailRead
         * @description A trip plus its ordered stops — what the Itinerary Builder/View loads.
         */
        TripDetailRead: {
            /** Budget Target */
            budget_target?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /**
             * Date End
             * Format: date
             */
            date_end: string;
            /**
             * Date Start
             * Format: date
             */
            date_start: string;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Public */
            is_public: boolean;
            /** Name */
            name: string;
            /** Share Token */
            share_token?: string | null;
            /**
             * Stops
             * @default []
             */
            stops: components["schemas"]["StopRead"][];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** TripRead */
        TripRead: {
            /** Budget Target */
            budget_target?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /**
             * Date End
             * Format: date
             */
            date_end: string;
            /**
             * Date Start
             * Format: date
             */
            date_start: string;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Public */
            is_public: boolean;
            /** Name */
            name: string;
            /** Share Token */
            share_token?: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * TripUpdate
         * @description PATCH /trips/{id}.
         *
         *     `is_public` is here, but `share_token` deliberately is NOT: the token is
         *     server-generated on first share and never regenerated implicitly
         *     (CONTRACTS §2), so it is not a client-settable field.
         */
        TripUpdate: {
            /** Budget Target */
            budget_target?: number | string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /** Date End */
            date_end?: string | null;
            /** Date Start */
            date_start?: string | null;
            /** Description */
            description?: string | null;
            /** Is Public */
            is_public?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /**
         * UserCreate
         * @description POST /auth/signup body (CONTRACTS §3).
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /**
         * UserRead
         * @description Public shape of a user. Deliberately has no `hashed_password` field,
         *     so a digest can never leak through a response model by accident.
         */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            /**
             * Saved Cities
             * @default []
             */
            saved_cities: components["schemas"]["CityBrief"][];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "catalog_manager" | "admin";
        /**
         * UserUpdate
         * @description PATCH /users/me body (CONTRACTS §3): name, language, saved_city_ids.
         */
        UserUpdate: {
            /** Language */
            language?: string | null;
            /** Name */
            name?: string | null;
            /** Saved City Ids */
            saved_city_ids?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_activities_activities_get: {
        parameters: {
            query?: {
                city_id?: string | null;
                category?: components["schemas"]["ActivityCategory"] | null;
                cost_max?: number | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_activity_activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_activity_activities__activity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_cities_cities_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive match on city or country */
                q?: string | null;
                country?: string | null;
                cost_max?: number | null;
                sort?: "popularity" | "cost" | "name";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_city_cities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_city_cities__city_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_city_cities__city_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    delete_itinerary_activity_itinerary_activities__itinerary_activity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itinerary_activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_itinerary_activity_itinerary_activities__itinerary_activity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itinerary_activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryActivityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_public_trip_public_trips__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicTripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_public_trip_public_trips__token__copy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_stops_stops_reorder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopReorderItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stop_stops__stop_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stop_activities_stops__stop_id__activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryActivityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_stop_activity_stops__stop_id__activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"][];
                };
            };
        };
    };
    create_trip_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_trip_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_plan_trips__trip_id__auto_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_budget_trips__trip_id__budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stops_trips__trip_id__stops_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stop_trips__trip_id__stops_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_me_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
